version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php_app
        restart: always
        volumes:
            - .:/var/www/html
        ports:
            - "8080:80"
        depends_on:
            - db
        networks:
            - app-network

    web:
        image: nginx:latest
        container_name: nginx_web
        restart: always
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        depends_on:
            - app
        networks:
            - app-network

    db:
        image: mariadb:latest
        container_name: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydb
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app-network

    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - .:/app
        working_dir: /app
        networks:
            - app-network

volumes:
    db_data:

networks:
    app-network:
        driver: bridge
